environment:
  nodejs_version: "18"

branches:
  only:
    - master  # ветка git
    - main

cache: node_modules  # кеширование

install:
  - ps: Install-Product node 20
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

before_build:
  - node -v
  - npm cache clean --force
  - rmdir /s /q node_modules\.cache || echo "No Webpack cache found"
  
build_script:
  - npm run build   # команда сборки

test_script:
  - npm run lint && npm test  # скрипт тестирования
